### ISSUE TITLE
won't work if bludit install in a subdirectory of the domain.

### ISSUE THREAD

**Issue by Larsene** [multicolor-rgb/front-admin-bar#1]
if bludit is installed in a subdir, the frontbar links won't work correctly.

instead of using `<?php echo DOMAIN;?>` 

i've fixed this using `<?php echo $site->url();?>`

anyway, thanks for this simple but great plugin !

**Comment by multicolor-rgb** [comment]
No problem, now i have a lot of work. But i hope before end this week i will upload fixed 2.0 version. Thanks for your suggestion:)

**Comment by multicolor-rgb** [comment]
v 2.0 done
