### ISSUE TITLE
The path to the admin panel in bar.php will not pass.

### ISSUE THREAD

**Issue by HATTANTOCO** [multicolor-rgb/front-admin-bar#2]
```
// Admin URI filter to access to the admin panel
define('ADMIN_URI_FILTER', 'admin');
```

If the above configuration changes are made, the path to the admin panel in bar.php will not pass.
Is it a specification to directly rewrite the path to each admin panel in bar.php?

**Comment by multicolor-rgb** [comment]
The static url redirect to /admin/ i check this and i fix soon how i can for support Admin_url_filter.

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/front-admin-bar/archive/refs/tags/2.0.1.zip

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/front-admin-bar/releases/tag/2.0.1
