### ISSUE TITLE
Make the front-admin-bar plugin responsive

### ISSUE THREAD

**Issue by HATTANTOCO** [multicolor-rgb/front-admin-bar#3]
Bludit administration screen is responsive, so why not make the front-admin-bar plugin responsive too?
I have created a sample.
In this case, it is impossible to make all the menus side-by-side, so a drop-down menu is used, with only icons in the smartphone view.
I also changed the icons to download only the necessary icons from the iconscout.com website as SVG files and use them. This is because, in my environment, there was an error loading the woff2 file.

I would very much appreciate your feedback.

https://user-images.githubusercontent.com/96756270/206903057-68e4223f-c193-4e32-9ce9-3a7328a0730a.mp4

**Comment by multicolor-rgb** [comment]
Hi! 
Thanks for yours feedback. I do it fixes before christmas comming:) 
If you like my work you can buy me ☕ 
https://paypal.me/multicol0r

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/front-admin-bar/releases/tag/3.0.0
