### ISSUE TITLE
No Front Admin Bar on preview pages

### ISSUE THREAD

**Issue by HATTANTOCO** [multicolor-rgb/front-admin-bar#4]
If the Front Admin Bar is displayed on the user screen that appears after clicking the preview button on the admin page, the preview page itself can be edited.
This unintentionally results in a congested editing of pages with identical content.
To prevent this, it is necessary to prevent the Front Admin Bar from being displayed on the preview page, but I do not know the conditional expression or function to determine the preview page.
I would be very grateful if you could modify this so that the Front Admin Bar is not displayed on preview pages.
Thank you in advance.

**Comment by multicolor-rgb** [comment]
Hi! 
Thanks for yours feedback. I do it fixes before christmas comming:)

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/front-admin-bar/releases/tag/3.0.0
